Data: https://drive.google.com/drive/folders/1AMHXFOjRsEaGNj3tA4eU9z8H_ZIV-Dnz?usp=share_link

In [1]:
## Import libraries
import pandas as pd

In [2]:
from IPython.display import display, HTML

css = """
.output {
    flex-direction: row;
}
"""

HTML('<style>{}</style>'.format(css))

In [3]:
dfc = pd.read_csv("updated-nyc-cdn.csv")
dfc

,Year,GeoType,Borough,Community District Number,updated_CDN,Community District Name,Total Population,Average household size,Children,Latino,White non-Hispanic,Black non-Hispanic,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units
0,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845","55,882","5,412","154,404","1,575","3,469","102,836","97,059","5,777"
1,2020.0,CD,Brooklyn,311,B11,Brooklyn Community District 11,"198,870",2.94,"42,380","31,489","72,496","2,353","86,067","1,081","5,384","71,074","67,236","3,838"
2,2020.0,CD,Queens,404,Q04,Queens Community District 4,"181,025",3.24,"38,213","93,972","9,329","7,679","65,963","1,692","2,390","57,748","55,202","2,546"
3,2020.0,CD,Queens,408,Q08,Queens Community District 8,"161,402",2.76,"32,754","29,486","44,302","18,682","60,413","3,200","5,319","59,385","56,623","2,762"
4,2020.0,CD,Queens,411,Q11,Queens Community District 11,"122,211",2.69,"21,612","14,460","41,967","2,641","59,980",779,"2,384","47,357","45,204","2,153"
5,2020.0,CD,Manhattan,103,M03,Manhattan Community District 3,"163,141",2.02,"18,955","38,668","55,048","12,776","50,188","1,425","5,036","82,589","76,335","6,254"
6,2020.0,CD,Queens,402,Q02,Queens Community District 2,"137,981",2.41,"21,892","40,659","39,290","3,784","48,826","1,563","3,859","60,766","56,413","4,353"
7,2020.0,CD,Brooklyn,312,B12,Brooklyn Community District 12,"205,377",3.47,"71,693","25,170","121,295","4,794","42,293","6,275","5,550","62,782","58,552","4,230"
8,2020.0,CD,Brooklyn,307,B07,Brooklyn Community District 7,"133,230",3.01,"30,146","52,310","31,915","4,209","40,415","1,120","3,261","45,683","43,079","2,604"
9,2020.0,CD,Queens,412,Q12,Queens Community District 12,"256,278",3.15,"54,033","46,287","4,607","138,219","38,934","13,450","14,781","84,092","79,827","4,265"
10,2020.0,CD,Queens,409,Q09,Queens Community District 9,"152,839",3.16,"31,566","63,620","23,074","10,224","38,802","9,768","7,351","50,877","48,117","2,760"
11,2020.0,CD,Queens,406,Q06,Queens Community District 6,"120,955",2.25,"20,995","19,946","53,244","3,490","37,288","1,637","5,350","56,695","53,485","3,210"
12,2020.0,CD,Queens,413,Q13,Queens Community District 13,"199,218",3.10,"35,861","24,911","18,192","102,711","36,954","7,057","9,393","66,259","63,211","3,048"
13,2020.0,CD,Brooklyn,310,B10,Brooklyn Community District 10,"136,071",2.58,"27,530","23,233","69,293","2,356","36,619","1,039","3,531","55,768","52,460","3,308"
14,2020.0,CD,Queens,403,Q03,Queens Community District 3,"179,134",3.16,"37,590","113,447","17,643","8,690","34,456","2,210","2,688","59,119","56,025","3,094"
15,2020.0,CD,Brooklyn,315,B15,Brooklyn Community District 15,"169,632",2.66,"36,851","15,688","105,734","6,649","34,358","1,296","5,907","67,322","63,097","4,225"
16,2020.0,CD,Queens,401,Q01,Queens Community District 1,"196,803",2.23,"27,312","50,073","90,578","15,281","29,989","3,037","7,845","90,547","85,697","4,850"
17,2020.0,CD,Queens,410,Q10,Queens Community District 10,"129,411",3.11,"24,525","30,587","25,678","17,971","27,838","16,205","11,132","43,252","41,213","2,039"
18,2020.0,CD,Manhattan,106,M06,Manhattan Community District 6,"155,614",1.73,"14,281","13,779","101,605","5,424","27,293","1,474","6,039","99,371","87,186","12,185"
19,2020.0,CD,Manhattan,108,M08,Manhattan Community District 8,"231,983",1.87,"33,594","18,517","170,406","6,257","26,536","1,789","8,478","138,922","122,565","16,357"
20,2020.0,CD,Staten Island,502,R02,Staten Island Community District 2,"140,795",2.83,"28,715","20,181","85,970","4,901","25,887","1,052","2,804","51,599","48,690","2,909"
21,2020.0,CD,Manhattan,104,M04,Manhattan Community District 4,"131,351",1.68,"11,444","23,249","69,509","9,075","22,933","1,258","5,327","84,357","75,001","9,356"
22,2020.0,CD,Manhattan,107,M07,Manhattan Community District 7,"222,129",1.93,"32,905","32,844","139,967","14,946","22,826","2,163","9,383","126,397","110,770","15,627"
23,2020.0,CD,Brooklyn,314,B14,Brooklyn Community District 14,"164,568",2.74,"36,180","24,726","61,736","46,445","21,317","2,332","8,012","62,254","59,355","2,899"
24,2020.0,CD,Bronx,209,X09,Bronx Community District 9,"188,249",2.82,"45,395","103,696","4,859","50,351","21,305","3,958","4,080","68,576","66,029","2,547"
25,2020.0,CD,Staten Island,501,R01,Staten Island Community District 1,"189,663",2.86,"44,216","58,955","62,560","40,093","20,632","1,995","5,428","69,066","64,940","4,126"
26,2020.0,CD,Queens,405,Q05,Queens Community District 5,"178,178",2.72,"33,591","64,221","85,642","3,884","19,241","1,658","3,532","69,416","65,075","4,341"
27,2020.0,CD,Brooklyn,313,B13,Brooklyn Community District 13,"108,905",2.39,"20,282","17,508","56,345","13,045","17,929",894,"3,184","46,672","44,531","2,141"
28,2020.0,CD,Brooklyn,302,B02,Brooklyn Community District 2,"130,021",2.03,"20,037","17,036","62,700","25,029","16,669","1,380","7,207","66,998","61,221","5,777"
29,2020.0,CD,Brooklyn,305,B05,Brooklyn Community District 5,"200,293",2.90,"48,268","73,681","6,341","92,108","14,772","4,469","8,922","72,381","68,174","4,207"
30,2020.0,CD,Manhattan,101,M01,Manhattan Community District 1,"78,390",2.02,"12,775","6,914","49,307","2,964","14,263",735,"4,207","41,977","36,457","5,520"
31,2020.0,CD,Brooklyn,301,B01,Brooklyn Community District 1,"204,125",2.43,"44,725","45,476","124,282","10,692","13,631","2,956","7,088","89,974","83,353","6,621"
32,2020.0,CD,Staten Island,503,R03,Staten Island Community District 3,"164,723",2.76,"33,271","17,659","129,182","1,791","12,212",839,"3,040","62,782","59,404","3,378"
33,2020.0,CD,Manhattan,105,M05,Manhattan Community District 5,"63,600",1.68,"5,982","7,912","35,750","4,768","12,123",632,"2,415","42,323","33,230","9,093"
34,2020.0,CD,Manhattan,102,M02,Manhattan Community District 2,"92,445",1.71,"8,587","7,303","65,968","2,271","11,922",828,"4,153","58,418","50,806","7,612"
35,2020.0,CD,Bronx,211,X11,Bronx Community District 11,"119,666",2.71,"25,881","53,788","26,285","23,567","11,154","1,822","3,050","44,864","42,686","2,178"
36,2020.0,CD,Manhattan,109,M09,Manhattan Community District 9,"110,458",2.34,"15,110","42,523","28,290","23,322","10,784","1,308","4,231","44,900","41,325","3,575"
37,2020.0,CD,Brooklyn,318,B18,Brooklyn Community District 18,"204,095",2.95,"43,137","17,919","43,259","120,661","10,486","2,452","9,318","72,361","68,523","3,838"
38,2020.0,CD,Bronx,207,X07,Bronx Community District 7,"146,813",2.79,"34,554","99,985","8,260","24,456","10,021","1,948","2,143","53,180","50,996","2,184"
39,2020.0,CD,Manhattan,111,M11,Manhattan Community District 11,"125,771",2.29,"23,954","56,743","18,865","35,311","9,825","1,249","3,778","54,738","51,823","2,915"
40,2020.0,CD,Bronx,210,X10,Bronx Community District 10,"130,763",2.45,"24,874","53,710","32,278","31,215","9,142","1,655","2,763","54,738","52,169","2,569"
41,2020.0,CD,Brooklyn,306,B06,Brooklyn Community District 6,"113,933",2.27,"23,278","18,136","69,749","10,285","8,372",967,"6,424","53,365","49,623","3,742"
42,2020.0,CD,Brooklyn,303,B03,Brooklyn Community District 3,"174,960",2.56,"36,035","32,788","46,592","76,676","7,988","2,542","8,374","72,904","67,225","5,679"
43,2020.0,CD,Brooklyn,304,B04,Brooklyn Community District 4,"120,747",2.69,"20,348","61,627","27,883","18,163","7,402","1,584","4,088","47,292","44,036","3,256"
44,2020.0,CD,Manhattan,112,M12,Manhattan Community District 12,"180,206",2.48,"28,290","117,244","38,222","13,161","5,751","1,679","4,149","74,722","71,076","3,646"
45,2020.0,CD,Brooklyn,308,B08,Brooklyn Community District 8,"108,259",2.30,"18,521","14,131","31,077","49,705","5,451","1,467","6,428","49,525","46,222","3,303"
46,2020.0,CD,Bronx,208,X08,Bronx Community District 8,"106,924",2.37,"20,729","52,317","34,097","11,247","5,329","1,279","2,655","45,144","42,569","2,575"
47,2020.0,CD,Manhattan,110,M10,Manhattan Community District 10,"130,440",2.19,"24,766","30,904","19,778","67,610","5,048","1,492","5,608","61,629","57,720","3,909"
48,2020.0,CD,Queens,414,Q14,Queens Community District 14,"124,173",2.70,"30,502","28,592","40,183","44,867","3,553","2,355","4,623","47,975","44,054","3,921"
49,2020.0,CD,Bronx,212,X12,Bronx Community District 12,"163,489",2.79,"36,764","44,168","9,347","98,995","3,440","3,008","4,531","60,856","57,603","3,253"
50,2020.0,CD,Brooklyn,317,B17,Brooklyn Community District 17,"162,446",2.71,"31,612","13,313","5,837","127,289","3,036","2,301","10,670","62,636","58,768","3,868"
51,2020.0,CD,Brooklyn,309,B09,Brooklyn Community District 9,"102,000",2.52,"19,983","10,478","28,532","52,807","2,640","2,279","5,264","41,694","39,338","2,356"
52,2020.0,CD,Bronx,204,X04,Bronx Community District 4,"150,436",2.79,"37,858","97,804","3,240","43,227","2,596","1,460","2,109","54,022","52,006","2,016"
53,2020.0,CD,Bronx,205,X05,Bronx Community District 5,"132,584",2.91,"34,523","90,730","1,991","34,598","1,888","1,536","1,841","45,814","44,332","1,482"
54,2020.0,CD,Brooklyn,316,B16,Brooklyn Community District 16,"98,506",2.68,"24,686","21,709","3,347","66,418","1,331","1,145","4,556","36,951","34,999","1,952"
55,2020.0,CD,Bronx,206,X06,Bronx Community District 6,"89,216",2.66,"23,194","56,181","5,653","23,765","1,148",936,"1,533","32,821","30,906","1,915"
56,2020.0,CD,Bronx,201,X01,Bronx Community District 1,"100,929",2.74,"27,218","67,216","2,556","27,765",909,936,"1,547","36,896","35,495","1,401"
57,2020.0,CD,Bronx,203,X03,Bronx Community District 3,"93,755",2.74,"25,748","52,646","1,538","36,599",518,882,"1,572","34,360","32,668","1,692"
58,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",941,"13,025",383,507,703,"19,240","18,381",859

In [4]:
dfc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 18 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   Year                       59 non-null     float64
 1   GeoType                    59 non-null     object
 2   Borough                    59 non-null     object
 3   Community District Number  59 non-null     int64
 4   updated_CDN                59 non-null     object
 5   Community District Name    59 non-null     object
 6   Total Population           59 non-null     object
 7   Average household size     59 non-null     float64
 8   Children                   59 non-null     object
 9   Latino                     59 non-null     object
 10  White non-Hispanic         59 non-null     object
 11  Black non-Hispanic         59 non-null     object
 12  Asian                      59 non-null     object
 13  Other race                 59 non-null     object
 14  Two or more races          59 non-null     object
 15  Total housing units        59 non-null     object
 16  Occupied housing units     59 non-null     object
 17  Vacant housing units       59 non-null     object
dtypes: float64(2), int64(1), object(15)
memory usage: 8.4+ KB

In [5]:
dfs = pd.read_csv("updated-snap-cdn.csv")
dfs

,Month,Boro,Community District,updated_cdn,BC_SNAP_Recipients,BC_SNAP_Households
0,9/1/20,Manhattan,M01,M01,2276,1799
1,9/1/20,Manhattan,M02,M02,2994,2438
2,9/1/20,Manhattan,M03,M03,37879,26041
3,9/1/20,Manhattan,M04,M04,13035,9802
4,9/1/20,Manhattan,M05,M05,6159,4317
...,...,...,...,...,...,...
1116,3/1/23,Queens,Q13,Q13,23430,14876
1117,3/1/23,Queens,Q14,Q14,31366,17378
1118,3/1/23,Staten Island,S01,R01,41354,22254
1119,3/1/23,Staten Island,S02,R02,18554,10695
1120,3/1/23,Staten Island,S03,R03,13658,8389

In [11]:
## rename columns header

dfs.columns = ["Month", "Borough", "Community District", "updated_CDN", "BC_SNAP_Recipients", "BC_SNAP_Households"]
dfs

,Month,Borough,Community District,updated_CDN,BC_SNAP_Recipients,BC_SNAP_Households
0,9/1/20,Manhattan,M01,M01,2276,1799
1,9/1/20,Manhattan,M02,M02,2994,2438
2,9/1/20,Manhattan,M03,M03,37879,26041
3,9/1/20,Manhattan,M04,M04,13035,9802
4,9/1/20,Manhattan,M05,M05,6159,4317
...,...,...,...,...,...,...
1116,3/1/23,Queens,Q13,Q13,23430,14876
1117,3/1/23,Queens,Q14,Q14,31366,17378
1118,3/1/23,Staten Island,S01,R01,41354,22254
1119,3/1/23,Staten Island,S02,R02,18554,10695
1120,3/1/23,Staten Island,S03,R03,13658,8389

In [12]:
dfs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1121 entries, 0 to 1120
Data columns (total 6 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   Month               1121 non-null   object
 1   Borough             1121 non-null   object
 2   Community District  1121 non-null   object
 3   updated_CDN         1121 non-null   object
 4   BC_SNAP_Recipients  1121 non-null   int64
 5   BC_SNAP_Households  1121 non-null   int64
dtypes: int64(2), object(4)
memory usage: 52.7+ KB

In [13]:
display(dfs)
display(dfc)

,Month,Borough,Community District,updated_CDN,BC_SNAP_Recipients,BC_SNAP_Households
0,9/1/20,Manhattan,M01,M01,2276,1799
1,9/1/20,Manhattan,M02,M02,2994,2438
2,9/1/20,Manhattan,M03,M03,37879,26041
3,9/1/20,Manhattan,M04,M04,13035,9802
4,9/1/20,Manhattan,M05,M05,6159,4317
...,...,...,...,...,...,...
1116,3/1/23,Queens,Q13,Q13,23430,14876
1117,3/1/23,Queens,Q14,Q14,31366,17378
1118,3/1/23,Staten Island,S01,R01,41354,22254
1119,3/1/23,Staten Island,S02,R02,18554,10695
1120,3/1/23,Staten Island,S03,R03,13658,8389

,Year,GeoType,Borough,Community District Number,updated_CDN,Community District Name,Total Population,Average household size,Children,Latino,White non-Hispanic,Black non-Hispanic,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units
0,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845","55,882","5,412","154,404","1,575","3,469","102,836","97,059","5,777"
1,2020.0,CD,Brooklyn,311,B11,Brooklyn Community District 11,"198,870",2.94,"42,380","31,489","72,496","2,353","86,067","1,081","5,384","71,074","67,236","3,838"
2,2020.0,CD,Queens,404,Q04,Queens Community District 4,"181,025",3.24,"38,213","93,972","9,329","7,679","65,963","1,692","2,390","57,748","55,202","2,546"
3,2020.0,CD,Queens,408,Q08,Queens Community District 8,"161,402",2.76,"32,754","29,486","44,302","18,682","60,413","3,200","5,319","59,385","56,623","2,762"
4,2020.0,CD,Queens,411,Q11,Queens Community District 11,"122,211",2.69,"21,612","14,460","41,967","2,641","59,980",779,"2,384","47,357","45,204","2,153"
5,2020.0,CD,Manhattan,103,M03,Manhattan Community District 3,"163,141",2.02,"18,955","38,668","55,048","12,776","50,188","1,425","5,036","82,589","76,335","6,254"
6,2020.0,CD,Queens,402,Q02,Queens Community District 2,"137,981",2.41,"21,892","40,659","39,290","3,784","48,826","1,563","3,859","60,766","56,413","4,353"
7,2020.0,CD,Brooklyn,312,B12,Brooklyn Community District 12,"205,377",3.47,"71,693","25,170","121,295","4,794","42,293","6,275","5,550","62,782","58,552","4,230"
8,2020.0,CD,Brooklyn,307,B07,Brooklyn Community District 7,"133,230",3.01,"30,146","52,310","31,915","4,209","40,415","1,120","3,261","45,683","43,079","2,604"
9,2020.0,CD,Queens,412,Q12,Queens Community District 12,"256,278",3.15,"54,033","46,287","4,607","138,219","38,934","13,450","14,781","84,092","79,827","4,265"
10,2020.0,CD,Queens,409,Q09,Queens Community District 9,"152,839",3.16,"31,566","63,620","23,074","10,224","38,802","9,768","7,351","50,877","48,117","2,760"
11,2020.0,CD,Queens,406,Q06,Queens Community District 6,"120,955",2.25,"20,995","19,946","53,244","3,490","37,288","1,637","5,350","56,695","53,485","3,210"
12,2020.0,CD,Queens,413,Q13,Queens Community District 13,"199,218",3.10,"35,861","24,911","18,192","102,711","36,954","7,057","9,393","66,259","63,211","3,048"
13,2020.0,CD,Brooklyn,310,B10,Brooklyn Community District 10,"136,071",2.58,"27,530","23,233","69,293","2,356","36,619","1,039","3,531","55,768","52,460","3,308"
14,2020.0,CD,Queens,403,Q03,Queens Community District 3,"179,134",3.16,"37,590","113,447","17,643","8,690","34,456","2,210","2,688","59,119","56,025","3,094"
15,2020.0,CD,Brooklyn,315,B15,Brooklyn Community District 15,"169,632",2.66,"36,851","15,688","105,734","6,649","34,358","1,296","5,907","67,322","63,097","4,225"
16,2020.0,CD,Queens,401,Q01,Queens Community District 1,"196,803",2.23,"27,312","50,073","90,578","15,281","29,989","3,037","7,845","90,547","85,697","4,850"
17,2020.0,CD,Queens,410,Q10,Queens Community District 10,"129,411",3.11,"24,525","30,587","25,678","17,971","27,838","16,205","11,132","43,252","41,213","2,039"
18,2020.0,CD,Manhattan,106,M06,Manhattan Community District 6,"155,614",1.73,"14,281","13,779","101,605","5,424","27,293","1,474","6,039","99,371","87,186","12,185"
19,2020.0,CD,Manhattan,108,M08,Manhattan Community District 8,"231,983",1.87,"33,594","18,517","170,406","6,257","26,536","1,789","8,478","138,922","122,565","16,357"
20,2020.0,CD,Staten Island,502,R02,Staten Island Community District 2,"140,795",2.83,"28,715","20,181","85,970","4,901","25,887","1,052","2,804","51,599","48,690","2,909"
21,2020.0,CD,Manhattan,104,M04,Manhattan Community District 4,"131,351",1.68,"11,444","23,249","69,509","9,075","22,933","1,258","5,327","84,357","75,001","9,356"
22,2020.0,CD,Manhattan,107,M07,Manhattan Community District 7,"222,129",1.93,"32,905","32,844","139,967","14,946","22,826","2,163","9,383","126,397","110,770","15,627"
23,2020.0,CD,Brooklyn,314,B14,Brooklyn Community District 14,"164,568",2.74,"36,180","24,726","61,736","46,445","21,317","2,332","8,012","62,254","59,355","2,899"
24,2020.0,CD,Bronx,209,X09,Bronx Community District 9,"188,249",2.82,"45,395","103,696","4,859","50,351","21,305","3,958","4,080","68,576","66,029","2,547"
25,2020.0,CD,Staten Island,501,R01,Staten Island Community District 1,"189,663",2.86,"44,216","58,955","62,560","40,093","20,632","1,995","5,428","69,066","64,940","4,126"
26,2020.0,CD,Queens,405,Q05,Queens Community District 5,"178,178",2.72,"33,591","64,221","85,642","3,884","19,241","1,658","3,532","69,416","65,075","4,341"
27,2020.0,CD,Brooklyn,313,B13,Brooklyn Community District 13,"108,905",2.39,"20,282","17,508","56,345","13,045","17,929",894,"3,184","46,672","44,531","2,141"
28,2020.0,CD,Brooklyn,302,B02,Brooklyn Community District 2,"130,021",2.03,"20,037","17,036","62,700","25,029","16,669","1,380","7,207","66,998","61,221","5,777"
29,2020.0,CD,Brooklyn,305,B05,Brooklyn Community District 5,"200,293",2.90,"48,268","73,681","6,341","92,108","14,772","4,469","8,922","72,381","68,174","4,207"
30,2020.0,CD,Manhattan,101,M01,Manhattan Community District 1,"78,390",2.02,"12,775","6,914","49,307","2,964","14,263",735,"4,207","41,977","36,457","5,520"
31,2020.0,CD,Brooklyn,301,B01,Brooklyn Community District 1,"204,125",2.43,"44,725","45,476","124,282","10,692","13,631","2,956","7,088","89,974","83,353","6,621"
32,2020.0,CD,Staten Island,503,R03,Staten Island Community District 3,"164,723",2.76,"33,271","17,659","129,182","1,791","12,212",839,"3,040","62,782","59,404","3,378"
33,2020.0,CD,Manhattan,105,M05,Manhattan Community District 5,"63,600",1.68,"5,982","7,912","35,750","4,768","12,123",632,"2,415","42,323","33,230","9,093"
34,2020.0,CD,Manhattan,102,M02,Manhattan Community District 2,"92,445",1.71,"8,587","7,303","65,968","2,271","11,922",828,"4,153","58,418","50,806","7,612"
35,2020.0,CD,Bronx,211,X11,Bronx Community District 11,"119,666",2.71,"25,881","53,788","26,285","23,567","11,154","1,822","3,050","44,864","42,686","2,178"
36,2020.0,CD,Manhattan,109,M09,Manhattan Community District 9,"110,458",2.34,"15,110","42,523","28,290","23,322","10,784","1,308","4,231","44,900","41,325","3,575"
37,2020.0,CD,Brooklyn,318,B18,Brooklyn Community District 18,"204,095",2.95,"43,137","17,919","43,259","120,661","10,486","2,452","9,318","72,361","68,523","3,838"
38,2020.0,CD,Bronx,207,X07,Bronx Community District 7,"146,813",2.79,"34,554","99,985","8,260","24,456","10,021","1,948","2,143","53,180","50,996","2,184"
39,2020.0,CD,Manhattan,111,M11,Manhattan Community District 11,"125,771",2.29,"23,954","56,743","18,865","35,311","9,825","1,249","3,778","54,738","51,823","2,915"
40,2020.0,CD,Bronx,210,X10,Bronx Community District 10,"130,763",2.45,"24,874","53,710","32,278","31,215","9,142","1,655","2,763","54,738","52,169","2,569"
41,2020.0,CD,Brooklyn,306,B06,Brooklyn Community District 6,"113,933",2.27,"23,278","18,136","69,749","10,285","8,372",967,"6,424","53,365","49,623","3,742"
42,2020.0,CD,Brooklyn,303,B03,Brooklyn Community District 3,"174,960",2.56,"36,035","32,788","46,592","76,676","7,988","2,542","8,374","72,904","67,225","5,679"
43,2020.0,CD,Brooklyn,304,B04,Brooklyn Community District 4,"120,747",2.69,"20,348","61,627","27,883","18,163","7,402","1,584","4,088","47,292","44,036","3,256"
44,2020.0,CD,Manhattan,112,M12,Manhattan Community District 12,"180,206",2.48,"28,290","117,244","38,222","13,161","5,751","1,679","4,149","74,722","71,076","3,646"
45,2020.0,CD,Brooklyn,308,B08,Brooklyn Community District 8,"108,259",2.30,"18,521","14,131","31,077","49,705","5,451","1,467","6,428","49,525","46,222","3,303"
46,2020.0,CD,Bronx,208,X08,Bronx Community District 8,"106,924",2.37,"20,729","52,317","34,097","11,247","5,329","1,279","2,655","45,144","42,569","2,575"
47,2020.0,CD,Manhattan,110,M10,Manhattan Community District 10,"130,440",2.19,"24,766","30,904","19,778","67,610","5,048","1,492","5,608","61,629","57,720","3,909"
48,2020.0,CD,Queens,414,Q14,Queens Community District 14,"124,173",2.70,"30,502","28,592","40,183","44,867","3,553","2,355","4,623","47,975","44,054","3,921"
49,2020.0,CD,Bronx,212,X12,Bronx Community District 12,"163,489",2.79,"36,764","44,168","9,347","98,995","3,440","3,008","4,531","60,856","57,603","3,253"
50,2020.0,CD,Brooklyn,317,B17,Brooklyn Community District 17,"162,446",2.71,"31,612","13,313","5,837","127,289","3,036","2,301","10,670","62,636","58,768","3,868"
51,2020.0,CD,Brooklyn,309,B09,Brooklyn Community District 9,"102,000",2.52,"19,983","10,478","28,532","52,807","2,640","2,279","5,264","41,694","39,338","2,356"
52,2020.0,CD,Bronx,204,X04,Bronx Community District 4,"150,436",2.79,"37,858","97,804","3,240","43,227","2,596","1,460","2,109","54,022","52,006","2,016"
53,2020.0,CD,Bronx,205,X05,Bronx Community District 5,"132,584",2.91,"34,523","90,730","1,991","34,598","1,888","1,536","1,841","45,814","44,332","1,482"
54,2020.0,CD,Brooklyn,316,B16,Brooklyn Community District 16,"98,506",2.68,"24,686","21,709","3,347","66,418","1,331","1,145","4,556","36,951","34,999","1,952"
55,2020.0,CD,Bronx,206,X06,Bronx Community District 6,"89,216",2.66,"23,194","56,181","5,653","23,765","1,148",936,"1,533","32,821","30,906","1,915"
56,2020.0,CD,Bronx,201,X01,Bronx Community District 1,"100,929",2.74,"27,218","67,216","2,556","27,765",909,936,"1,547","36,896","35,495","1,401"
57,2020.0,CD,Bronx,203,X03,Bronx Community District 3,"93,755",2.74,"25,748","52,646","1,538","36,599",518,882,"1,572","34,360","32,668","1,692"
58,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",941,"13,025",383,507,703,"19,240","18,381",859

In [14]:
df1 = pd.merge(dfc,dfs)
df1

,Year,GeoType,Borough,Community District Number,updated_CDN,Community District Name,Total Population,Average household size,Children,Latino,...,Asian,Other race,Two or more races,Total housing units,Occupied housing units,Vacant housing units,Month,Community District,BC_SNAP_Recipients,BC_SNAP_Households
0,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845",...,"154,404","1,575","3,469","102,836","97,059","5,777",9/1/20,Q07,28354,18494
1,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845",...,"154,404","1,575","3,469","102,836","97,059","5,777",12/1/20,Q07,27903,18278
2,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845",...,"154,404","1,575","3,469","102,836","97,059","5,777",3/1/21,Q07,28863,18855
3,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845",...,"154,404","1,575","3,469","102,836","97,059","5,777",6/1/21,Q07,30056,19665
4,2020.0,CD,Queens,407,Q07,Queens Community District 7,"269,587",2.75,"45,543","48,845",...,"154,404","1,575","3,469","102,836","97,059","5,777",9/1/21,Q07,29813,19525
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
821,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",...,383,507,703,"19,240","18,381",859,3/1/20,B02,20279,11294
822,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",...,383,507,703,"19,240","18,381",859,6/1/20,B02,22420,12426
823,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",...,383,507,703,"19,240","18,381",859,9/1/22,B02,22883,12945
824,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",...,383,507,703,"19,240","18,381",859,12/1/22,B02,23422,13240
825,2020.0,CD,Bronx,202,X02,Bronx Community District 2,"54,454",2.82,"14,652","38,895",...,383,507,703,"19,240","18,381",859,3/1/23,B02,23795,13544

In [39]:
df = df1[['Year', 'Borough','updated_CDN', 'Asian', 'BC_SNAP_Recipients', 'BC_SNAP_Households', 'Average household size',
          'Total housing units', 'Occupied housing units', 'Vacant housing units', 'Month']]
df

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
0,2020.0,Queens,Q07,"154,404",28354,18494,2.75,"102,836","97,059","5,777",9/1/20
1,2020.0,Queens,Q07,"154,404",27903,18278,2.75,"102,836","97,059","5,777",12/1/20
2,2020.0,Queens,Q07,"154,404",28863,18855,2.75,"102,836","97,059","5,777",3/1/21
3,2020.0,Queens,Q07,"154,404",30056,19665,2.75,"102,836","97,059","5,777",6/1/21
4,2020.0,Queens,Q07,"154,404",29813,19525,2.75,"102,836","97,059","5,777",9/1/21
...,...,...,...,...,...,...,...,...,...,...,...
821,2020.0,Bronx,X02,383,20279,11294,2.82,"19,240","18,381",859,3/1/20
822,2020.0,Bronx,X02,383,22420,12426,2.82,"19,240","18,381",859,6/1/20
823,2020.0,Bronx,X02,383,22883,12945,2.82,"19,240","18,381",859,9/1/22
824,2020.0,Bronx,X02,383,23422,13240,2.82,"19,240","18,381",859,12/1/22
825,2020.0,Bronx,X02,383,23795,13544,2.82,"19,240","18,381",859,3/1/23

In [16]:
df.query

<bound method DataFrame.query of        Year Borough updated_CDN      Community District Name    Asian  \
0    2020.0  Queens         Q07  Queens Community District 7  154,404
1    2020.0  Queens         Q07  Queens Community District 7  154,404
2    2020.0  Queens         Q07  Queens Community District 7  154,404
3    2020.0  Queens         Q07  Queens Community District 7  154,404
4    2020.0  Queens         Q07  Queens Community District 7  154,404
..      ...     ...         ...                          ...      ...
821  2020.0   Bronx         X02   Bronx Community District 2      383
822  2020.0   Bronx         X02   Bronx Community District 2      383
823  2020.0   Bronx         X02   Bronx Community District 2      383
824  2020.0   Bronx         X02   Bronx Community District 2      383
825  2020.0   Bronx         X02   Bronx Community District 2      383

     BC_SNAP_Recipients  BC_SNAP_Households  Average household size  \
0                 28354               18494                    2.75
1                 27903               18278                    2.75
2                 28863               18855                    2.75
3                 30056               19665                    2.75
4                 29813               19525                    2.75
..                  ...                 ...                     ...
821               20279               11294                    2.82
822               22420               12426                    2.82
823               22883               12945                    2.82
824               23422               13240                    2.82
825               23795               13544                    2.82

    Total housing units Occupied housing units Vacant housing units    Month
0               102,836                 97,059                5,777   9/1/20
1               102,836                 97,059                5,777  12/1/20
2               102,836                 97,059                5,777   3/1/21
3               102,836                 97,059                5,777   6/1/21
4               102,836                 97,059                5,777   9/1/21
..                  ...                    ...                  ...      ...
821              19,240                 18,381                  859   3/1/20
822              19,240                 18,381                  859   6/1/20
823              19,240                 18,381                  859   9/1/22
824              19,240                 18,381                  859  12/1/22
825              19,240                 18,381                  859   3/1/23

[826 rows x 12 columns]>

In [17]:
df.sample(20)

,Year,Borough,updated_CDN,Community District Name,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
753,2020.0,Bronx,X05,Bronx Community District 5,"1,888",55413,31556,2.91,"45,814","44,332","1,482",9/1/22
313,2020.0,Manhattan,M07,Manhattan Community District 7,"22,826",17484,12948,1.93,"126,397","110,770","15,627",12/1/21
92,2020.0,Queens,Q02,Queens Community District 2,"48,826",9719,6223,2.41,"60,766","56,413","4,353",12/1/19
23,2020.0,Brooklyn,B11,Brooklyn Community District 11,"86,067",32328,19687,2.94,"71,074","67,236","3,838",3/1/20
123,2020.0,Brooklyn,B07,Brooklyn Community District 7,"40,415",22841,14168,3.01,"45,683","43,079","2,604",9/1/22
527,2020.0,Brooklyn,B18,Brooklyn Community District 18,"10,486",26534,16181,2.95,"72,361","68,523","3,838",3/1/20
752,2020.0,Bronx,X05,Bronx Community District 5,"1,888",54815,30212,2.91,"45,814","44,332","1,482",6/1/20
458,2020.0,Staten Island,R03,Staten Island Community District 3,"12,212",12360,7639,2.76,"62,782","59,404","3,378",6/1/22
824,2020.0,Bronx,X02,Bronx Community District 2,383,23422,13240,2.82,"19,240","18,381",859,12/1/22
562,2020.0,Bronx,X10,Bronx Community District 10,"9,142",20358,12349,2.45,"54,738","52,169","2,569",3/1/21
286,2020.0,Staten Island,R02,Staten Island Community District 2,"25,887",16719,9747,2.83,"51,599","48,690","2,909",3/1/22
588,2020.0,Brooklyn,B03,Brooklyn Community District 3,"7,988",46697,25904,2.56,"72,904","67,225","5,679",9/1/20
307,2020.0,Manhattan,M04,Manhattan Community District 4,"22,933",13971,10474,1.68,"84,357","75,001","9,356",3/1/23
721,2020.0,Brooklyn,B09,Brooklyn Community District 9,"2,640",21626,13478,2.52,"41,694","39,338","2,356",6/1/22
578,2020.0,Brooklyn,B06,Brooklyn Community District 6,"8,372",11574,7558,2.27,"53,365","49,623","3,742",9/1/21
487,2020.0,Manhattan,M02,Manhattan Community District 2,"11,922",2992,2391,1.71,"58,418","50,806","7,612",9/1/22
265,2020.0,Manhattan,M06,Manhattan Community District 6,"27,293",5938,4988,1.73,"99,371","87,186","12,185",3/1/23
57,2020.0,Queens,Q11,Queens Community District 11,"59,980",7591,4996,2.69,"47,357","45,204","2,153",12/1/20
25,2020.0,Brooklyn,B11,Brooklyn Community District 11,"86,067",39946,23612,2.94,"71,074","67,236","3,838",9/1/22
276,2020.0,Manhattan,M08,Manhattan Community District 8,"26,536",5758,4515,1.87,"138,922","122,565","16,357",6/1/20

In [31]:
df.sort_values(by="Borough", ascending = True)

,Year,Borough,updated_CDN,Community District Name,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
825,2020.0,Bronx,X02,Bronx Community District 2,383.0,23795,13544,2.82,"19,240","18,381",859,3/1/23
652,2020.0,Bronx,X08,Bronx Community District 8,NaN,15151,9150,2.37,"45,144","42,569","2,575",12/1/19
651,2020.0,Bronx,X08,Bronx Community District 8,NaN,18818,11375,2.37,"45,144","42,569","2,575",6/1/22
650,2020.0,Bronx,X08,Bronx Community District 8,NaN,19012,11550,2.37,"45,144","42,569","2,575",3/1/22
649,2020.0,Bronx,X08,Bronx Community District 8,NaN,18324,11148,2.37,"45,144","42,569","2,575",12/1/21
...,...,...,...,...,...,...,...,...,...,...,...,...
288,2020.0,Staten Island,R02,Staten Island Community District 2,NaN,13789,8187,2.83,"51,599","48,690","2,909",3/1/20
289,2020.0,Staten Island,R02,Staten Island Community District 2,NaN,15293,8931,2.83,"51,599","48,690","2,909",6/1/20
291,2020.0,Staten Island,R02,Staten Island Community District 2,NaN,17267,9995,2.83,"51,599","48,690","2,909",9/1/22
448,2020.0,Staten Island,R03,Staten Island Community District 3,NaN,11396,7091,2.76,"62,782","59,404","3,378",9/1/20
451,2020.0,Staten Island,R03,Staten Island Community District 3,NaN,11784,7321,2.76,"62,782","59,404","3,378",6/1/21

In [33]:
df.sort_values(by="updated_CDN", ascending = True)

,Year,Borough,updated_CDN,Community District Name,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
436,2020.0,Brooklyn,B01,Brooklyn Community District 1,NaN,52233,21536,2.43,"89,974","83,353","6,621",3/1/21
434,2020.0,Brooklyn,B01,Brooklyn Community District 1,NaN,53243,21872,2.43,"89,974","83,353","6,621",9/1/20
435,2020.0,Brooklyn,B01,Brooklyn Community District 1,NaN,51257,21182,2.43,"89,974","83,353","6,621",12/1/20
437,2020.0,Brooklyn,B01,Brooklyn Community District 1,NaN,53124,22027,2.43,"89,974","83,353","6,621",6/1/21
438,2020.0,Brooklyn,B01,Brooklyn Community District 1,NaN,51887,21226,2.43,"89,974","83,353","6,621",9/1/21
...,...,...,...,...,...,...,...,...,...,...,...,...
697,2020.0,Bronx,X12,Bronx Community District 12,NaN,41733,23224,2.79,"60,856","57,603","3,253",9/1/22
698,2020.0,Bronx,X12,Bronx Community District 12,NaN,42761,23728,2.79,"60,856","57,603","3,253",12/1/22
699,2020.0,Bronx,X12,Bronx Community District 12,NaN,43737,24481,2.79,"60,856","57,603","3,253",3/1/23
686,2020.0,Bronx,X12,Bronx Community District 12,NaN,40805,22463,2.79,"60,856","57,603","3,253",9/1/20
692,2020.0,Bronx,X12,Bronx Community District 12,NaN,42168,23527,2.79,"60,856","57,603","3,253",3/1/22

In [34]:
df["Borough"].unique()

array(['Queens', 'Brooklyn', 'Manhattan', 'Staten Island', 'Bronx'],
      dtype=object)

In [35]:
df["updated_CDN"].unique()

array(['Q07', 'B11', 'Q04', 'Q08', 'Q11', 'M03', 'Q02', 'B12', 'B07',
       'Q12', 'Q09', 'Q06', 'Q13', 'B10', 'Q03', 'B15', 'Q01', 'Q10',
       'M06', 'M08', 'R02', 'M04', 'M07', 'B14', 'X09', 'R01', 'Q05',
       'B13', 'B02', 'B05', 'M01', 'B01', 'R03', 'M05', 'M02', 'X11',
       'M09', 'B18', 'X07', 'M11', 'X10', 'B06', 'B03', 'B04', 'M12',
       'B08', 'X08', 'M10', 'Q14', 'X12', 'B17', 'B09', 'X04', 'X05',
       'B16', 'X06', 'X01', 'X03', 'X02'], dtype=object)

In [36]:
df["Community District Name"].unique()

array(['Queens Community District 7', 'Brooklyn Community District 11',
       'Queens Community District 4', 'Queens Community District 8',
       'Queens Community District 11', 'Manhattan Community District 3',
       'Queens Community District 2', 'Brooklyn Community District 12',
       'Brooklyn Community District 7', 'Queens Community District 12',
       'Queens Community District 9', 'Queens Community District 6',
       'Queens Community District 13', 'Brooklyn Community District 10',
       'Queens Community District 3', 'Brooklyn Community District 15',
       'Queens Community District 1', 'Queens Community District 10',
       'Manhattan Community District 6', 'Manhattan Community District 8',
       'Staten Island Community District 2',
       'Manhattan Community District 4', 'Manhattan Community District 7',
       'Brooklyn Community District 14', 'Bronx Community District 9',
       'Staten Island Community District 1',
       'Queens Community District 5', 'Brooklyn Community District 13',
       'Brooklyn Community District 2', 'Brooklyn Community District 5',
       'Manhattan Community District 1', 'Brooklyn Community District 1',
       'Staten Island Community District 3',
       'Manhattan Community District 5', 'Manhattan Community District 2',
       'Bronx Community District 11', 'Manhattan Community District 9',
       'Brooklyn Community District 18', 'Bronx Community District 7',
       'Manhattan Community District 11', 'Bronx Community District 10',
       'Brooklyn Community District 6', 'Brooklyn Community District 3',
       'Brooklyn Community District 4', 'Manhattan Community District 12',
       'Brooklyn Community District 8', 'Bronx Community District 8',
       'Manhattan Community District 10', 'Queens Community District 14',
       'Bronx Community District 12', 'Brooklyn Community District 17',
       'Brooklyn Community District 9', 'Bronx Community District 4',
       'Bronx Community District 5', 'Brooklyn Community District 16',
       'Bronx Community District 6', 'Bronx Community District 1',
       'Bronx Community District 3', 'Bronx Community District 2'],
      dtype=object)

In [38]:
df["Month"].unique()

array(['9/1/20', '12/1/20', '3/1/21', '6/1/21', '9/1/21', '12/1/21',
       '3/1/22', '6/1/22', '12/1/19', '3/1/20', '6/1/20', '9/1/22',
       '12/1/22', '3/1/23'], dtype=object)

In [47]:
df.query("Month == '9/1/20'")

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
0,2020.0,Queens,Q07,"154,404",28354,18494,2.75,"102,836","97,059","5,777",9/1/20
14,2020.0,Brooklyn,B11,"86,067",36796,21874,2.94,"71,074","67,236","3,838",9/1/20
28,2020.0,Queens,Q04,"65,963",27250,15787,3.24,"57,748","55,202","2,546",9/1/20
42,2020.0,Queens,Q08,"60,413",19237,11464,2.76,"59,385","56,623","2,762",9/1/20
56,2020.0,Queens,Q11,"59,980",7626,5033,2.69,"47,357","45,204","2,153",9/1/20
70,2020.0,Manhattan,M03,"50,188",37879,26041,2.02,"82,589","76,335","6,254",9/1/20
84,2020.0,Queens,Q02,"48,826",11731,7355,2.41,"60,766","56,413","4,353",9/1/20
98,2020.0,Brooklyn,B12,"42,293",62525,20597,3.47,"62,782","58,552","4,230",9/1/20
112,2020.0,Brooklyn,B07,"40,415",21759,13160,3.01,"45,683","43,079","2,604",9/1/20
126,2020.0,Queens,Q12,"38,934",47792,28803,3.15,"84,092","79,827","4,265",9/1/20
140,2020.0,Queens,Q09,"38,802",23776,13674,3.16,"50,877","48,117","2,760",9/1/20
154,2020.0,Queens,Q06,"37,288",10780,7395,2.25,"56,695","53,485","3,210",9/1/20
168,2020.0,Queens,Q13,"36,954",22301,14059,3.10,"66,259","63,211","3,048",9/1/20
182,2020.0,Brooklyn,B10,"36,619",18480,10988,2.58,"55,768","52,460","3,308",9/1/20
196,2020.0,Queens,Q03,"34,456",25576,14672,3.16,"59,119","56,025","3,094",9/1/20
210,2020.0,Brooklyn,B15,"34,358",28671,17944,2.66,"67,322","63,097","4,225",9/1/20
224,2020.0,Queens,Q01,"29,989",24865,14936,2.23,"90,547","85,697","4,850",9/1/20
238,2020.0,Queens,Q10,"27,838",17636,10528,3.11,"43,252","41,213","2,039",9/1/20
252,2020.0,Manhattan,M06,"27,293",5550,4773,1.73,"99,371","87,186","12,185",9/1/20
266,2020.0,Manhattan,M08,"26,536",6009,4680,1.87,"138,922","122,565","16,357",9/1/20
280,2020.0,Staten Island,R02,"25,887",15810,9214,2.83,"51,599","48,690","2,909",9/1/20
294,2020.0,Manhattan,M04,"22,933",13035,9802,1.68,"84,357","75,001","9,356",9/1/20
308,2020.0,Manhattan,M07,"22,826",17310,12817,1.93,"126,397","110,770","15,627",9/1/20
322,2020.0,Brooklyn,B14,"21,317",32143,19171,2.74,"62,254","59,355","2,899",9/1/20
336,2020.0,Bronx,X09,"21,305",56722,31336,2.82,"68,576","66,029","2,547",9/1/20
350,2020.0,Staten Island,R01,"20,632",39400,20918,2.86,"69,066","64,940","4,126",9/1/20
364,2020.0,Queens,Q05,"19,241",20237,11840,2.72,"69,416","65,075","4,341",9/1/20
378,2020.0,Brooklyn,B13,"17,929",32606,21761,2.39,"46,672","44,531","2,141",9/1/20
392,2020.0,Brooklyn,B02,"16,669",14517,9883,2.03,"66,998","61,221","5,777",9/1/20
406,2020.0,Brooklyn,B05,"14,772",67886,39365,2.90,"72,381","68,174","4,207",9/1/20
420,2020.0,Manhattan,M01,"14,263",2276,1799,2.02,"41,977","36,457","5,520",9/1/20
434,2020.0,Brooklyn,B01,"13,631",53243,21872,2.43,"89,974","83,353","6,621",9/1/20
448,2020.0,Staten Island,R03,"12,212",11396,7091,2.76,"62,782","59,404","3,378",9/1/20
462,2020.0,Manhattan,M05,"12,123",6159,4317,1.68,"42,323","33,230","9,093",9/1/20
476,2020.0,Manhattan,M02,"11,922",2994,2438,1.71,"58,418","50,806","7,612",9/1/20
490,2020.0,Bronx,X11,"11,154",26117,15220,2.71,"44,864","42,686","2,178",9/1/20
504,2020.0,Manhattan,M09,"10,784",23273,15315,2.34,"44,900","41,325","3,575",9/1/20
518,2020.0,Brooklyn,B18,"10,486",31455,19046,2.95,"72,361","68,523","3,838",9/1/20
532,2020.0,Bronx,X07,"10,021",48615,27942,2.79,"53,180","50,996","2,184",9/1/20
546,2020.0,Manhattan,M11,"9,825",43970,27654,2.29,"54,738","51,823","2,915",9/1/20
560,2020.0,Bronx,X10,"9,142",20119,12173,2.45,"54,738","52,169","2,569",9/1/20
574,2020.0,Brooklyn,B06,"8,372",11464,7584,2.27,"53,365","49,623","3,742",9/1/20
588,2020.0,Brooklyn,B03,"7,988",46697,25904,2.56,"72,904","67,225","5,679",9/1/20
602,2020.0,Brooklyn,B04,"7,402",25812,16297,2.69,"47,292","44,036","3,256",9/1/20
616,2020.0,Manhattan,M12,"5,751",47223,32431,2.48,"74,722","71,076","3,646",9/1/20
630,2020.0,Brooklyn,B08,"5,451",21157,14040,2.30,"49,525","46,222","3,303",9/1/20
644,2020.0,Bronx,X08,"5,329",18344,10971,2.37,"45,144","42,569","2,575",9/1/20
658,2020.0,Manhattan,M10,"5,048",32474,20991,2.19,"61,629","57,720","3,909",9/1/20
672,2020.0,Queens,Q14,"3,553",30889,16829,2.70,"47,975","44,054","3,921",9/1/20
686,2020.0,Bronx,X12,"3,440",40805,22463,2.79,"60,856","57,603","3,253",9/1/20
700,2020.0,Brooklyn,B17,"3,036",32954,21224,2.71,"62,636","58,768","3,868",9/1/20
714,2020.0,Brooklyn,B09,"2,640",22023,13644,2.52,"41,694","39,338","2,356",9/1/20
728,2020.0,Bronx,X04,"2,596",58248,32582,2.79,"54,022","52,006","2,016",9/1/20
742,2020.0,Bronx,X05,"1,888",56964,31471,2.91,"45,814","44,332","1,482",9/1/20
756,2020.0,Brooklyn,B16,"1,331",40015,22838,2.68,"36,951","34,999","1,952",9/1/20
770,2020.0,Bronx,X06,"1,148",40944,22427,2.66,"32,821","30,906","1,915",9/1/20
784,2020.0,Bronx,X01,909,47212,25740,2.74,"36,896","35,495","1,401",9/1/20
798,2020.0,Bronx,X03,518,45086,24750,2.74,"34,360","32,668","1,692",9/1/20
812,2020.0,Bronx,X02,383,23150,12855,2.82,"19,240","18,381",859,9/1/20

In [44]:
df.query("Month == '12/1/20'")

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
1,2020.0,Queens,Q07,"154,404",27903,18278,2.75,"102,836","97,059","5,777",12/1/20
15,2020.0,Brooklyn,B11,"86,067",35835,21477,2.94,"71,074","67,236","3,838",12/1/20
29,2020.0,Queens,Q04,"65,963",26564,15373,3.24,"57,748","55,202","2,546",12/1/20
43,2020.0,Queens,Q08,"60,413",18747,11224,2.76,"59,385","56,623","2,762",12/1/20
57,2020.0,Queens,Q11,"59,980",7591,4996,2.69,"47,357","45,204","2,153",12/1/20
71,2020.0,Manhattan,M03,"50,188",36972,25354,2.02,"82,589","76,335","6,254",12/1/20
85,2020.0,Queens,Q02,"48,826",11522,7216,2.41,"60,766","56,413","4,353",12/1/20
99,2020.0,Brooklyn,B12,"42,293",59486,19831,3.47,"62,782","58,552","4,230",12/1/20
113,2020.0,Brooklyn,B07,"40,415",21162,12911,3.01,"45,683","43,079","2,604",12/1/20
127,2020.0,Queens,Q12,"38,934",45928,27735,3.15,"84,092","79,827","4,265",12/1/20
141,2020.0,Queens,Q09,"38,802",23229,13415,3.16,"50,877","48,117","2,760",12/1/20
155,2020.0,Queens,Q06,"37,288",10659,7307,2.25,"56,695","53,485","3,210",12/1/20
169,2020.0,Queens,Q13,"36,954",21922,13756,3.10,"66,259","63,211","3,048",12/1/20
183,2020.0,Brooklyn,B10,"36,619",18082,10778,2.58,"55,768","52,460","3,308",12/1/20
197,2020.0,Queens,Q03,"34,456",24765,14250,3.16,"59,119","56,025","3,094",12/1/20
211,2020.0,Brooklyn,B15,"34,358",27676,17471,2.66,"67,322","63,097","4,225",12/1/20
225,2020.0,Queens,Q01,"29,989",24107,14563,2.23,"90,547","85,697","4,850",12/1/20
239,2020.0,Queens,Q10,"27,838",17104,10332,3.11,"43,252","41,213","2,039",12/1/20
253,2020.0,Manhattan,M06,"27,293",5383,4582,1.73,"99,371","87,186","12,185",12/1/20
267,2020.0,Manhattan,M08,"26,536",5950,4637,1.87,"138,922","122,565","16,357",12/1/20
281,2020.0,Staten Island,R02,"25,887",15478,9027,2.83,"51,599","48,690","2,909",12/1/20
295,2020.0,Manhattan,M04,"22,933",12912,9703,1.68,"84,357","75,001","9,356",12/1/20
309,2020.0,Manhattan,M07,"22,826",16999,12550,1.93,"126,397","110,770","15,627",12/1/20
323,2020.0,Brooklyn,B14,"21,317",31096,18663,2.74,"62,254","59,355","2,899",12/1/20
337,2020.0,Bronx,X09,"21,305",54999,30515,2.82,"68,576","66,029","2,547",12/1/20
351,2020.0,Staten Island,R01,"20,632",38258,20359,2.86,"69,066","64,940","4,126",12/1/20
365,2020.0,Queens,Q05,"19,241",19649,11574,2.72,"69,416","65,075","4,341",12/1/20
379,2020.0,Brooklyn,B13,"17,929",31600,21215,2.39,"46,672","44,531","2,141",12/1/20
393,2020.0,Brooklyn,B02,"16,669",13870,9515,2.03,"66,998","61,221","5,777",12/1/20
407,2020.0,Brooklyn,B05,"14,772",64642,37679,2.90,"72,381","68,174","4,207",12/1/20
421,2020.0,Manhattan,M01,"14,263",2211,1709,2.02,"41,977","36,457","5,520",12/1/20
435,2020.0,Brooklyn,B01,"13,631",51257,21182,2.43,"89,974","83,353","6,621",12/1/20
449,2020.0,Staten Island,R03,"12,212",11284,7013,2.76,"62,782","59,404","3,378",12/1/20
463,2020.0,Manhattan,M05,"12,123",6014,4257,1.68,"42,323","33,230","9,093",12/1/20
477,2020.0,Manhattan,M02,"11,922",2963,2407,1.71,"58,418","50,806","7,612",12/1/20
491,2020.0,Bronx,X11,"11,154",25471,14864,2.71,"44,864","42,686","2,178",12/1/20
505,2020.0,Manhattan,M09,"10,784",22386,14826,2.34,"44,900","41,325","3,575",12/1/20
519,2020.0,Brooklyn,B18,"10,486",29904,18219,2.95,"72,361","68,523","3,838",12/1/20
533,2020.0,Bronx,X07,"10,021",47059,27206,2.79,"53,180","50,996","2,184",12/1/20
547,2020.0,Manhattan,M11,"9,825",42630,26858,2.29,"54,738","51,823","2,915",12/1/20
561,2020.0,Bronx,X10,"9,142",19741,12008,2.45,"54,738","52,169","2,569",12/1/20
575,2020.0,Brooklyn,B06,"8,372",11243,7401,2.27,"53,365","49,623","3,742",12/1/20
589,2020.0,Brooklyn,B03,"7,988",43981,24535,2.56,"72,904","67,225","5,679",12/1/20
603,2020.0,Brooklyn,B04,"7,402",24490,15670,2.69,"47,292","44,036","3,256",12/1/20
617,2020.0,Manhattan,M12,"5,751",45845,31591,2.48,"74,722","71,076","3,646",12/1/20
631,2020.0,Brooklyn,B08,"5,451",19928,13254,2.30,"49,525","46,222","3,303",12/1/20
645,2020.0,Bronx,X08,"5,329",17915,10761,2.37,"45,144","42,569","2,575",12/1/20
659,2020.0,Manhattan,M10,"5,048",30998,20155,2.19,"61,629","57,720","3,909",12/1/20
673,2020.0,Queens,Q14,"3,553",29379,16221,2.70,"47,975","44,054","3,921",12/1/20
687,2020.0,Bronx,X12,"3,440",39777,21969,2.79,"60,856","57,603","3,253",12/1/20
701,2020.0,Brooklyn,B17,"3,036",31428,20375,2.71,"62,636","58,768","3,868",12/1/20
715,2020.0,Brooklyn,B09,"2,640",20863,13093,2.52,"41,694","39,338","2,356",12/1/20
729,2020.0,Bronx,X04,"2,596",55972,31491,2.79,"54,022","52,006","2,016",12/1/20
743,2020.0,Bronx,X05,"1,888",54750,30436,2.91,"45,814","44,332","1,482",12/1/20
757,2020.0,Brooklyn,B16,"1,331",37370,21604,2.68,"36,951","34,999","1,952",12/1/20
771,2020.0,Bronx,X06,"1,148",39669,21738,2.66,"32,821","30,906","1,915",12/1/20
785,2020.0,Bronx,X01,909,45563,24989,2.74,"36,896","35,495","1,401",12/1/20
799,2020.0,Bronx,X03,518,43446,23953,2.74,"34,360","32,668","1,692",12/1/20
813,2020.0,Bronx,X02,383,22329,12438,2.82,"19,240","18,381",859,12/1/20

In [48]:
df.query("Month == '3/1/20'")

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
9,2020.0,Queens,Q07,"154,404",24845,16613,2.75,"102,836","97,059","5,777",3/1/20
23,2020.0,Brooklyn,B11,"86,067",32328,19687,2.94,"71,074","67,236","3,838",3/1/20
37,2020.0,Queens,Q04,"65,963",22450,13300,3.24,"57,748","55,202","2,546",3/1/20
51,2020.0,Queens,Q08,"60,413",16125,9969,2.76,"59,385","56,623","2,762",3/1/20
65,2020.0,Queens,Q11,"59,980",6524,4431,2.69,"47,357","45,204","2,153",3/1/20
79,2020.0,Manhattan,M03,"50,188",34830,23982,2.02,"82,589","76,335","6,254",3/1/20
93,2020.0,Queens,Q02,"48,826",9720,6212,2.41,"60,766","56,413","4,353",3/1/20
107,2020.0,Brooklyn,B12,"42,293",57542,18790,3.47,"62,782","58,552","4,230",3/1/20
121,2020.0,Brooklyn,B07,"40,415",19136,11555,3.01,"45,683","43,079","2,604",3/1/20
135,2020.0,Queens,Q12,"38,934",40088,24661,3.15,"84,092","79,827","4,265",3/1/20
149,2020.0,Queens,Q09,"38,802",19214,11370,3.16,"50,877","48,117","2,760",3/1/20
163,2020.0,Queens,Q06,"37,288",9248,6653,2.25,"56,695","53,485","3,210",3/1/20
177,2020.0,Queens,Q13,"36,954",17835,11660,3.10,"66,259","63,211","3,048",3/1/20
191,2020.0,Brooklyn,B10,"36,619",15961,9573,2.58,"55,768","52,460","3,308",3/1/20
205,2020.0,Queens,Q03,"34,456",21029,12324,3.16,"59,119","56,025","3,094",3/1/20
219,2020.0,Brooklyn,B15,"34,358",25811,16391,2.66,"67,322","63,097","4,225",3/1/20
233,2020.0,Queens,Q01,"29,989",20896,12771,2.23,"90,547","85,697","4,850",3/1/20
247,2020.0,Queens,Q10,"27,838",14519,8898,3.11,"43,252","41,213","2,039",3/1/20
261,2020.0,Manhattan,M06,"27,293",4897,4224,1.73,"99,371","87,186","12,185",3/1/20
275,2020.0,Manhattan,M08,"26,536",5218,4164,1.87,"138,922","122,565","16,357",3/1/20
288,2020.0,Staten Island,R02,"25,887",13789,8187,2.83,"51,599","48,690","2,909",3/1/20
303,2020.0,Manhattan,M04,"22,933",11414,8584,1.68,"84,357","75,001","9,356",3/1/20
317,2020.0,Manhattan,M07,"22,826",15570,11645,1.93,"126,397","110,770","15,627",3/1/20
331,2020.0,Brooklyn,B14,"21,317",27714,16800,2.74,"62,254","59,355","2,899",3/1/20
345,2020.0,Bronx,X09,"21,305",48708,27052,2.82,"68,576","66,029","2,547",3/1/20
358,2020.0,Staten Island,R01,"20,632",34592,18454,2.86,"69,066","64,940","4,126",3/1/20
373,2020.0,Queens,Q05,"19,241",16273,9685,2.72,"69,416","65,075","4,341",3/1/20
387,2020.0,Brooklyn,B13,"17,929",30029,20314,2.39,"46,672","44,531","2,141",3/1/20
401,2020.0,Brooklyn,B02,"16,669",12731,8649,2.03,"66,998","61,221","5,777",3/1/20
415,2020.0,Brooklyn,B05,"14,772",59085,34172,2.90,"72,381","68,174","4,207",3/1/20
429,2020.0,Manhattan,M01,"14,263",2201,1795,2.02,"41,977","36,457","5,520",3/1/20
443,2020.0,Brooklyn,B01,"13,631",49022,19574,2.43,"89,974","83,353","6,621",3/1/20
456,2020.0,Staten Island,R03,"12,212",9553,6129,2.76,"62,782","59,404","3,378",3/1/20
471,2020.0,Manhattan,M05,"12,123",5592,3857,1.68,"42,323","33,230","9,093",3/1/20
485,2020.0,Manhattan,M02,"11,922",2628,2146,1.71,"58,418","50,806","7,612",3/1/20
499,2020.0,Bronx,X11,"11,154",22136,13061,2.71,"44,864","42,686","2,178",3/1/20
513,2020.0,Manhattan,M09,"10,784",20339,13475,2.34,"44,900","41,325","3,575",3/1/20
527,2020.0,Brooklyn,B18,"10,486",26534,16181,2.95,"72,361","68,523","3,838",3/1/20
541,2020.0,Bronx,X07,"10,021",41865,24217,2.79,"53,180","50,996","2,184",3/1/20
555,2020.0,Manhattan,M11,"9,825",39350,24851,2.29,"54,738","51,823","2,915",3/1/20
569,2020.0,Bronx,X10,"9,142",16879,10411,2.45,"54,738","52,169","2,569",3/1/20
583,2020.0,Brooklyn,B06,"8,372",9908,6592,2.27,"53,365","49,623","3,742",3/1/20
597,2020.0,Brooklyn,B03,"7,988",40998,22347,2.56,"72,904","67,225","5,679",3/1/20
611,2020.0,Brooklyn,B04,"7,402",21920,13739,2.69,"47,292","44,036","3,256",3/1/20
625,2020.0,Manhattan,M12,"5,751",41300,28799,2.48,"74,722","71,076","3,646",3/1/20
639,2020.0,Brooklyn,B08,"5,451",18716,12293,2.30,"49,525","46,222","3,303",3/1/20
653,2020.0,Bronx,X08,"5,329",15194,9190,2.37,"45,144","42,569","2,575",3/1/20
667,2020.0,Manhattan,M10,"5,048",28931,18788,2.19,"61,629","57,720","3,909",3/1/20
681,2020.0,Queens,Q14,"3,553",27358,15004,2.70,"47,975","44,054","3,921",3/1/20
695,2020.0,Bronx,X12,"3,440",34877,19262,2.79,"60,856","57,603","3,253",3/1/20
709,2020.0,Brooklyn,B17,"3,036",27712,17932,2.71,"62,636","58,768","3,868",3/1/20
723,2020.0,Brooklyn,B09,"2,640",19137,11873,2.52,"41,694","39,338","2,356",3/1/20
737,2020.0,Bronx,X04,"2,596",50360,28414,2.79,"54,022","52,006","2,016",3/1/20
751,2020.0,Bronx,X05,"1,888",49525,27397,2.91,"45,814","44,332","1,482",3/1/20
765,2020.0,Brooklyn,B16,"1,331",35363,20091,2.68,"36,951","34,999","1,952",3/1/20
779,2020.0,Bronx,X06,"1,148",36637,20047,2.66,"32,821","30,906","1,915",3/1/20
793,2020.0,Bronx,X01,909,41545,22736,2.74,"36,896","35,495","1,401",3/1/20
807,2020.0,Bronx,X03,518,39250,21694,2.74,"34,360","32,668","1,692",3/1/20
821,2020.0,Bronx,X02,383,20279,11294,2.82,"19,240","18,381",859,3/1/20

In [49]:
df.query("Month == '6/1/20'")

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
10,2020.0,Queens,Q07,"154,404",27266,17848,2.75,"102,836","97,059","5,777",6/1/20
24,2020.0,Brooklyn,B11,"86,067",35284,21152,2.94,"71,074","67,236","3,838",6/1/20
38,2020.0,Queens,Q04,"65,963",25613,14884,3.24,"57,748","55,202","2,546",6/1/20
52,2020.0,Queens,Q08,"60,413",18376,11043,2.76,"59,385","56,623","2,762",6/1/20
66,2020.0,Queens,Q11,"59,980",7279,4848,2.69,"47,357","45,204","2,153",6/1/20
80,2020.0,Manhattan,M03,"50,188",37082,25467,2.02,"82,589","76,335","6,254",6/1/20
94,2020.0,Queens,Q02,"48,826",11059,6956,2.41,"60,766","56,413","4,353",6/1/20
108,2020.0,Brooklyn,B12,"42,293",61108,20089,3.47,"62,782","58,552","4,230",6/1/20
122,2020.0,Brooklyn,B07,"40,415",20917,12648,3.01,"45,683","43,079","2,604",6/1/20
136,2020.0,Queens,Q12,"38,934",45667,27581,3.15,"84,092","79,827","4,265",6/1/20
150,2020.0,Queens,Q09,"38,802",22539,13053,3.16,"50,877","48,117","2,760",6/1/20
164,2020.0,Queens,Q06,"37,288",10437,7238,2.25,"56,695","53,485","3,210",6/1/20
178,2020.0,Queens,Q13,"36,954",20743,13267,3.10,"66,259","63,211","3,048",6/1/20
192,2020.0,Brooklyn,B10,"36,619",17758,10583,2.58,"55,768","52,460","3,308",6/1/20
206,2020.0,Queens,Q03,"34,456",24106,13884,3.16,"59,119","56,025","3,094",6/1/20
220,2020.0,Brooklyn,B15,"34,358",28044,17558,2.66,"67,322","63,097","4,225",6/1/20
234,2020.0,Queens,Q01,"29,989",23598,14255,2.23,"90,547","85,697","4,850",6/1/20
248,2020.0,Queens,Q10,"27,838",16714,10036,3.11,"43,252","41,213","2,039",6/1/20
262,2020.0,Manhattan,M06,"27,293",5326,4568,1.73,"99,371","87,186","12,185",6/1/20
276,2020.0,Manhattan,M08,"26,536",5758,4515,1.87,"138,922","122,565","16,357",6/1/20
289,2020.0,Staten Island,R02,"25,887",15293,8931,2.83,"51,599","48,690","2,909",6/1/20
304,2020.0,Manhattan,M04,"22,933",12539,9382,1.68,"84,357","75,001","9,356",6/1/20
318,2020.0,Manhattan,M07,"22,826",16785,12440,1.93,"126,397","110,770","15,627",6/1/20
332,2020.0,Brooklyn,B14,"21,317",30806,18449,2.74,"62,254","59,355","2,899",6/1/20
346,2020.0,Bronx,X09,"21,305",54171,29984,2.82,"68,576","66,029","2,547",6/1/20
359,2020.0,Staten Island,R01,"20,632",38088,20244,2.86,"69,066","64,940","4,126",6/1/20
374,2020.0,Queens,Q05,"19,241",19173,11268,2.72,"69,416","65,075","4,341",6/1/20
388,2020.0,Brooklyn,B13,"17,929",32014,21398,2.39,"46,672","44,531","2,141",6/1/20
402,2020.0,Brooklyn,B02,"16,669",14123,9614,2.03,"66,998","61,221","5,777",6/1/20
416,2020.0,Brooklyn,B05,"14,772",65389,37915,2.90,"72,381","68,174","4,207",6/1/20
430,2020.0,Manhattan,M01,"14,263",2280,1807,2.02,"41,977","36,457","5,520",6/1/20
444,2020.0,Brooklyn,B01,"13,631",52201,21241,2.43,"89,974","83,353","6,621",6/1/20
457,2020.0,Staten Island,R03,"12,212",10946,6853,2.76,"62,782","59,404","3,378",6/1/20
472,2020.0,Manhattan,M05,"12,123",6165,4171,1.68,"42,323","33,230","9,093",6/1/20
486,2020.0,Manhattan,M02,"11,922",2912,2362,1.71,"58,418","50,806","7,612",6/1/20
500,2020.0,Bronx,X11,"11,154",24988,14618,2.71,"44,864","42,686","2,178",6/1/20
514,2020.0,Manhattan,M09,"10,784",22436,14766,2.34,"44,900","41,325","3,575",6/1/20
528,2020.0,Brooklyn,B18,"10,486",30261,18310,2.95,"72,361","68,523","3,838",6/1/20
542,2020.0,Bronx,X07,"10,021",46703,26848,2.79,"53,180","50,996","2,184",6/1/20
556,2020.0,Manhattan,M11,"9,825",42554,26742,2.29,"54,738","51,823","2,915",6/1/20
570,2020.0,Bronx,X10,"9,142",19215,11713,2.45,"54,738","52,169","2,569",6/1/20
584,2020.0,Brooklyn,B06,"8,372",11010,7289,2.27,"53,365","49,623","3,742",6/1/20
598,2020.0,Brooklyn,B03,"7,988",45155,24965,2.56,"72,904","67,225","5,679",6/1/20
612,2020.0,Brooklyn,B04,"7,402",24696,15570,2.69,"47,292","44,036","3,256",6/1/20
626,2020.0,Manhattan,M12,"5,751",45712,31442,2.48,"74,722","71,076","3,646",6/1/20
640,2020.0,Brooklyn,B08,"5,451",20630,13608,2.30,"49,525","46,222","3,303",6/1/20
654,2020.0,Bronx,X08,"5,329",17567,10506,2.37,"45,144","42,569","2,575",6/1/20
668,2020.0,Manhattan,M10,"5,048",31343,20295,2.19,"61,629","57,720","3,909",6/1/20
682,2020.0,Queens,Q14,"3,553",29808,16209,2.70,"47,975","44,054","3,921",6/1/20
696,2020.0,Bronx,X12,"3,440",38867,21459,2.79,"60,856","57,603","3,253",6/1/20
710,2020.0,Brooklyn,B17,"3,036",31527,20294,2.71,"62,636","58,768","3,868",6/1/20
724,2020.0,Brooklyn,B09,"2,640",21313,13145,2.52,"41,694","39,338","2,356",6/1/20
738,2020.0,Bronx,X04,"2,596",56155,31479,2.79,"54,022","52,006","2,016",6/1/20
752,2020.0,Bronx,X05,"1,888",54815,30212,2.91,"45,814","44,332","1,482",6/1/20
766,2020.0,Brooklyn,B16,"1,331",38889,22149,2.68,"36,951","34,999","1,952",6/1/20
780,2020.0,Bronx,X06,"1,148",39679,21713,2.66,"32,821","30,906","1,915",6/1/20
794,2020.0,Bronx,X01,909,45637,24832,2.74,"36,896","35,495","1,401",6/1/20
808,2020.0,Bronx,X03,518,43317,23789,2.74,"34,360","32,668","1,692",6/1/20
822,2020.0,Bronx,X02,383,22420,12426,2.82,"19,240","18,381",859,6/1/20

In [71]:
## QUERY year w/2020 / months w/2020 / by borough

df_2020 = df.query("2020 <= Year \
& Month == ['3/1/20', '6/1/20', '9/1/20', '12/1/20'] \
& Borough == ['Queens', 'Manhattan', 'Staten Island', 'Brooklyn', 'Bronx']")
df_2020

,Year,Borough,updated_CDN,Asian,BC_SNAP_Recipients,BC_SNAP_Households,Average household size,Total housing units,Occupied housing units,Vacant housing units,Month
0,2020.0,Queens,Q07,"154,404",28354,18494,2.75,"102,836","97,059","5,777",9/1/20
1,2020.0,Queens,Q07,"154,404",27903,18278,2.75,"102,836","97,059","5,777",12/1/20
9,2020.0,Queens,Q07,"154,404",24845,16613,2.75,"102,836","97,059","5,777",3/1/20
10,2020.0,Queens,Q07,"154,404",27266,17848,2.75,"102,836","97,059","5,777",6/1/20
14,2020.0,Brooklyn,B11,"86,067",36796,21874,2.94,"71,074","67,236","3,838",9/1/20
...,...,...,...,...,...,...,...,...,...,...,...
808,2020.0,Bronx,X03,518,43317,23789,2.74,"34,360","32,668","1,692",6/1/20
812,2020.0,Bronx,X02,383,23150,12855,2.82,"19,240","18,381",859,9/1/20
813,2020.0,Bronx,X02,383,22329,12438,2.82,"19,240","18,381",859,12/1/20
821,2020.0,Bronx,X02,383,20279,11294,2.82,"19,240","18,381",859,3/1/20
822,2020.0,Bronx,X02,383,22420,12426,2.82,"19,240","18,381",859,6/1/20

In [74]:
df_2020["Year"].value_counts().sort_index(ascending = False)

2020.0    236
Name: Year, dtype: int64

In [83]:
df.query("'Queens' == 'Borough' & Asian == 'BC_SNAP_Recipients'")

Empty DataFrame
Columns: [Year, Borough, updated_CDN, Asian, BC_SNAP_Recipients, BC_SNAP_Households, Average household size, Total housing units, Occupied housing units, Vacant housing units, Month]
Index: []